build:
  environment:
    php:
      version: 5.5
  tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
checks:
    php:
      code_rating: true
      duplication: true
