build:
  environment:
    php:
      version: 5.6
  dependencies:
          before:
              - cp app/config/parameters.yml.ci app/config/parameters.yml
              - cp app/config/parameters.yml app/config/parameters.yml.dist
              - composer install --prefer-source
              - php app/console doctrine:database:create --env=test
              - php app/console doctrine:schema:create --env=test
checks:
    php:
        code_rating: true
        duplication: true
filter:
    paths: [src/*]