order_tracking_backend:
    resource: "@OrderTrackingBackendBundle/Resources/config/routing.yml"
    prefix:   /

order_tracking_frontend:
    resource: "@OrderTrackingFrontendBundle/Resources/config/routing.yml"
    prefix:   /

order_tracking_pedido:
    resource: "@OrderTrackingFrontendBundle/Controller"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"