order_tracking_pedido:
    resource: "@OrderTrackingFrontendBundle/Controller"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

order_tracking_pedido_backend:
    resource: "@OrderTrackingBackendBundle/Controller"
    type:     annotation

