order_tracking_backend:
    resource: "@OrderTrackingBackendBundle/Resources/config/routing.yml"
    prefix:   /

order_tracking_frontend:
    resource: "@OrderTrackingFrontendBundle/Resources/config/routing.yml"
    prefix:   /