api_rest:
    type:     rest
    prefix:   /api/v1
    defaults: {_format: json}
    resource: OrderTracking\RestBundle\Controller\DefaultController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   backend/api/doc